### ISSUE TITLE
Results of manual clustering not saving? 

### ISSUE THREAD

**Issue by seqasim** [jniediek/combinato#24]
After manually sorting the results from combinato (all negative spikes), I have looked at the data in sort_neg_simple/sort_cat.h5. While the timestamp on the file would indicate that it updates after I save my results in the gui, it doesn't seem like the actual results of my manual clustering are saving - all of the results match that of the initial automatic clustering.

**Comment by jniediek** [comment]
Hi @seqasim, I just tested this with some negative spikes and found no problems: I saved changes in the GUI, closed the GUI, opened it again and all manual changes were still there. I then confirmed that the sort_cat.h5 file was changed correctly.

Some wild guesses what might have gone wrong in your case:
- no write permissions in the folder where the data is stored
- forgot to use the `--neg` option to `css-prepare-sorting` and `css-combine`
- looked at the `groups_orig` array instead of the `groups` array

Were there any error messages on the command line?

**Comment by seqasim** [comment]
Hi @jniediek, sorry, just noticed a muted error message on the command line when trying to save: 

python[55894:12113509] modalSession has been exited prematurely - check for a reentrant call to endModalSession:

Not sure what to make of that.

**Comment by jniediek** [comment]
What version of python are you using? This error doesn't come from combinato directly.

**Comment by seqasim** [comment]
I'm using 2.7 - is this a compatibility issue perhaps?

**Comment by jniediek** [comment]
I don't know where the modalSession comes from, what operating system are you on, and are you using the Anaconda distribution?

**Comment by seqasim** [comment]
I am using OSX El Capitan, and I am using the anaconda distro. 

It seems this may be OSX specific: https://forum.qt.io/topic/43618/modal-sessions-with-pyqt4-and-os-x

I will try this on our cluster (rather than my personal laptop) and report back.

**Comment by jniediek** [comment]
https://bugreports.qt.io/browse/QTBUG-37699 is also a report of this problem

**Comment by seqasim** [comment]
Thanks @jniediek - this seems to have been the problem. Works fine on the (Linux-based) cluster.

**Comment by jniediek** [comment]
Cool, thanks for testing. As soon as I have some spare time, I'll do the Qt5 version of combinato. This will most likely also fix this issue on OSX.
