### ISSUE TITLE
Amplitude of waveforms 

### ISSUE THREAD

**Issue by seqasim** [jniediek/combinato#25]
Hi @jniediek, 

I am using Combinato with Blackrock data (.ns6 files). I extract each channel and save it into a mat file with amplitude in uV (so each "spike" is usually ~ 100 uV). 

However, the waveforms plotted in the gui and that are output in the sort_cat.h5 file are scaled up by some magnitude, ending up as roughly ~ 3500-8000 *mystery* units. Compare this to the simulation_5.mat file that is downloadable in the tutorial, in which the raw trace is of magnitude < 10 and the waveforms end up ~100-200 uV. 

Is the data being scaled up by roughly ~ 80x at some point in the extraction process? I have looked around but have not been able to find this. This does not seem to be a problem with the neuralynx data.

**Comment by seqasim** [comment]
I believe I found the answer. 

In the extract directory's tools.py, the function read_matfile scales the data by a parameter DEFAULT_MAT_VOLT_FACTOR. This is set to 100 by default. Setting it to 1 solved the issue.

**Comment by jniediek** [comment]
Hi @seqasim, great you found the answer yourself!

As you will have noticed, combinato was mostly developed with Neuralynx files in mind. I'll now add some reference to the `DEFAULT_MAT_VOLT_FACTOR` to the documentation.

**Comment by melinat** [comment]
Hi, 
I'm working with the same data (blackrock ns6 files) in the same lab as Salman. 
I'm using the updated code, and it looks like tools.py in the extract directory no longer does any scaling (no DEFAULT_MAT_VOLT_FACTOR, and you can do this in the command line now as you specified above). However, my data still seems to have a scaling issue - was anything other than this scaling factor changed?

**Comment by jniediek** [comment]
Hi @melinat,
two questions might be in order to sort this out:
- Is your scaling issue the same as the one @seqasim had reported earlier? If not, can you specify how much your resulting spikes differ from what you expect?
- Do you see the message `Rescaling matfile data by (factor)` in the command line output, where (factor) is not 1?

**Comment by melinat** [comment]
Hi @jniediek thank you for your quick response!
My scaling issue does not seem to be the same. 
For example, for a channel that he found 3 units in, of amplitudes ~50,100,150 uV I find units in the range 200 - 600 uV (so closer to a **4x increase in amplitude**).
I don't see a message "rescaling mafile... " anywhere in the output. 
I'm not sure where a factor of 4 could be introduced, especially because I can't seem to find anywhere that scaling occurs or that the scaling value isn't set to 1. Do you have any ideas?

**Comment by seqasim** [comment]
@jniediek @melinat 

I've found the issue.... this was my mistake, should have spotted it earlier. That factor of 4 is the key. 

This is Blackrock data, and the raw .ns6 neural data is stored by default as digital values. The input range of the front-end amplifier is +/-8191 uV, and is digitized over 16 bits, so to carry out the conversion from bits to uV is (2*8191)/(2^16-1) = 0.25, or divide by 4.

I remembered that I account for this by setting my DEFAULT_MAT_VOLT_FACTOR = 0.25 rather than 1.
