### ISSUE TITLE
css-gui: Function of "Artifact" button in the gui

### ISSUE THREAD

**Issue by seqasim** [jniediek/combinato#26]
<img width="188" alt="screen shot 2017-03-20 at 11 08 39 am" src="https://cloud.githubusercontent.com/assets/15975112/24106280/ca1a923a-0d5d-11e7-9d3a-0228408d04b6.png">

Hey @jniediek ,

I was wondering if the Artifact button (pictured above) could have the same outcome as pressing "A" on the keyboard. When you press A, you send a cluster to the Artifact grouping. However, clicking the Artifact button pictured above does not seem to send a cluster to the Artifact grouping. 

This is most helpful when you have a channel that's trash and you want to classify everything as artifact, it can take a while to go through everything by pressing A on the keyboard.

**Comment by jniediek** [comment]
Hey @seqasim,

pressing `A` sends one cluster to the artifact group and the artifact button marks the group as artifact, without moving clusters.

A quick way to move an entire group to the artifact group is to go to the "Correlations" tab, select the group you would like to move as "Group 1" and "Artifacts" as "Group 2", and push the "Merge" button. This would merge your selected group to the artifact group in one step, without the hassle of pressing `A` for each cluster.

Speaking about the "Correlations" tab, make sure to use its "Merge" button also to merge two groups of clusters in general, instead of clicking on each cluster, one by one, in the "All groups" tab.

I will not change the behavior of the Artifact button, but I could add an additional button "Move group to artifacts" to the "One Group" tab. Do you think that would be useful?

**Comment by seqasim** [comment]
Hi @jniediek, 

Thanks for the reply. What you've said re: the Correlations tab makes perfect sense. I don't think another button would be necessary, though it might worth noting in the wiki that marking the group as "Artifact" with the artifact button does not in fact move the clusters to the artifact grouping?

**Comment by jniediek** [comment]
Thanks for reporting back. I added some explanation to the wiki: https://github.com/jniediek/combinato/wiki/Tutorial-Real-Data#42-using-the-graphical-user-interface
