### ISSUE TITLE
Running recent code on Windows

### ISSUE THREAD

**Issue by loublanpain** [jniediek/combinato#39]
I ran Combinato's most recent code on Windows with Python version 3.7.6 and I get the following error message when using css-gui in Git Bash:
```
$ css-gui
/usr/bin/env: ‘python3’: No such file or directory
```

I believe this is because on Windows, python is called via ```python``` instead of the flexibility we have with a mac, where calling ```python3``` is the same as ```python```. So the shebang line at the begining of the css-gui script (and other scripts) ```#!/usr/bin/env python3``` leads to the error. I have manually changed the shebang line to ```#!/usr/bin/env python``` and it seems to get rid of the error.

Is there a way to modify scripts with a shebang line that "adapts" depending on the platform detected, i.e. with an if/else statement?

Thanks!

**Comment by jniediek** [comment]
Thanks for the report! I don't think there's a direct solution to this problem. Maybe you can symlink your `python.exe` to a `python3.exe`, so that you don't have to change the combinato scripts?

In an ideal world, I would have created only one main script for combinato, that would take the different sorting steps as arguments, something like

`combinato cluster .....`
`combinato prepare ....`

I hope I'll do this at some point. Then it'll be straightforward to modify the shebang of `combinato`.

I'll leave the issue open for now.
