### ISSUE TITLE
python setup_options.py giving error

### ISSUE THREAD

**Issue by umarshahzad-lm** [jniediek/combinato#58]
C:\Users\username\combinato>python setup_options.py
Could not execute SPC binary C:\Users\Umar Shahzad\combinato\spc\cluster_64.exe
[WinError 193] %1 is not a valid Win32 application

Kindly help me. im using windows

**Comment by jniediek** [comment]
My first guess is that there's a problem with spaces or quotation marks in the file `options.py`, in the following line:

`CLUS_BINARY = '/home/johannes/Repositories/combinato/spc/cluster_linux64.exe'

(there'll be a different path in your case).

You might either have to correct the path there, or to prepend the letter `r` to the path string, something like

`CLUS_BINARY = r'your\path'`

If that doesn't help, get back to this issue here.

Best,
Johannes
